version: "3.9"
services:
  db:
    container_name: postgres-container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5439:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    container_name: redis-container
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  test-db:
    container_name: test-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

    
volumes:
  db-data:
  redis-data: